- name: Launch compute instance
  gather_facts: false
  hosts: 10.100.100.200
  tasks:
    - name: Create a new instance and attaches to a port
      os_server:
        auth:
          auth_url: "{{auth_url}}"
          username: "{{username}}"
          password: "{{password}}"
          project_name: "{{project_name}}"
          user_domain_name: default
          project_domain_name: default
        state: present
        name: "{{machine_name}}"
        image: "{{image}}"
        key_name: debian_key
        timeout: 200
        flavor: "{{flavor}}"
        nics: 
          - port-name: "{{port_name}}"
      register: server_facts 
    - debug:
        msg: "{{server_facts}}"
    - name: Check if everything gone ok
      fail:
        msg: "Machine with specified name exists"
      when: not server_facts.changed 