- name: Launch a compute instance
  gather_facts: false
  hosts: all
  tasks:
    - name: Create a new instance and attaches to a network and passes metadata to the instance
      os_server:
        state: present
        auth:
          auth_url: "{{auth_url}}"
          username: "{{username}}"
          password: "{{password}}"
          project_name: "{{project_name}}"
          user_domain_name: default
          project_domain_name: default
        name: "{{machine_name}}"
        image: "{{image}}"
        key_name: "{{key_name}}"
        timeout: "{{timeout}}"
        flavor: "{{flavor}}"
        network: "{{network}}"