- name: Launch a compute instance
  hosts: all
  tasks:
    - name: Launch a VM
      os_server:
        image: Ubuntu 14.04 LTS x64
        name: vm1
        key_name: my_keypair_dd2d
        availability_zone: nova
        flavor: 22
        state: present
        network: floatingIPv4