- name: Destroy an instance
  gather_facts: false
  hosts: 10.100.100.200
  tasks:
    - name: Destroy instance by name
      os_server:
        state: absent
        auth:
          auth_url: "{{auth_url}}"
          username: "{{username}}"
          password: "{{password}}"
          project_name: "{{project_name}}"
          user_domain_name: default
          project_domain_name: default
        name: "{{machine_name}}"
      register: server_fact_name
      when: machine_name is defined and not machine_name == ''
      
    - name: Destroy instance by ip address
      os_server:
        state: absent
        auth:
          auth_url: "{{auth_url}}"
          username: "{{username}}"
          password: "{{password}}"
          project_name: "{{project_name}}"
          user_domain_name: default
          project_domain_name: default
          nics: 
           - port-name: "{{port_name}}"
          register: server_fact_ip
      when: server_fact_name is not defined and port_name is defined
    - debug:
        msg: "No credintials attached"
      when: server_fact_name is not defined and server_fact_ip is not defined
        