- name: Launch a compute instance
  gather_facts: false
  hosts: all
  tasks:
    - name: destroy
      os_server:
        state: absent
        auth:
          auth_url: "{{auth_url}}"
          username: "{{username}}"
          password: "{{password}}"
          project_name: "{{project_name}}"
          user_domain_name: default
          project_domain_name: default
        name: "{{machine_name}}"