- name: Stop the instance
  gather_facts: true
  hosts: 10.100.100.200
  vars:
    time: "{{ansible_date_time['iso8601']}}"
    file: "{{machine_name + '_' + time}}"
  tasks:
    - name: Stop
      os_server_action:
        auth:
          auth_url: "{{auth_url}}"
          username: "{{username}}"
          password: "{{password}}"
          project_name: "{{project_name}}"
          user_domain_name: default
          project_domain_name: default
        action: stop
        server: "{{machine_name}}"
    - name: wait 60s
      wait_for: timeout=60
    - name: get instance facts
      os_server_facts:
        auth:
          auth_url: "{{auth_url}}"
          username: "{{username}}"
          password: "{{password}}"
          project_name: "{{project_name}}"
          user_domain_name: default
          project_domain_name: default
        server: "{{machine_name}}"
      register: server_fact
    - debug:
        msg: "{{server_fact}}"
    - name: Check if everything gone ok
      fail:
        msg: "Machine havent stop"
      when: server_fact['ansible_facts']['openstack_servers'][0]['vm_state'] != 'stopped'
    - name: make backup image
      command: source /home/os/admin-openrc && nova image-create --poll {{machine_name | quote}} {{ file | quote}}
    - name: wait 120s
      wait_for: timeout=120
    - name:
      os_image_facts:
        auth:
          auth_url: "{{auth_url}}"
          username: "{{username}}"
          password: "{{password}}"
          project_name: "{{project_name}}"
          user_domain_name: default
          project_domain_name: default
        image: "{{file}}"
      register: image_fact
    - debug:
        msg: "{{image_fact}}"
    
      
    
      
    
      