- hosts: "{{port_name}}"
  gather_facts: False
  become: true
  tasks:
    - name: Update resolv.conf
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf
    - name: Update and upgrade
      apt:
        upgrade: yes
        update_cache: yes
    
      
     
