- name: Wait for port 22 to be ready
  hosts: localhost
  gather_facts: False
  tasks:
    - wait_for:
        host: "{{port_name}}"
        port: 22
        search_regex: OpenSSH
        delay: 10
        timeout: 600